blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/[OWNER]/bc-docker/discussions
    about: Usa Discussions para preguntas generales y conversaciones
  - name: 📚 Documentación Docker
    url: https://docs.docker.com/
    about: Documentación oficial de Docker
